### ISSUE TITLE
muse-io signals

### ISSUE THREAD

**Issue by cristinasegalin** [alexandrebarachant/muse-lsl#102]
HI, thanks a lot for your contribution!

The library is already helpful as it is. 
I was wondering if it was possible to get some function to return the absolute and relative band signals and session score as you would get when connecting muse-io and checking /muse/elements, concentration from /muse/experimental/concentration

Thank you !

**Comment by jdpigeon** [comment]
There's currently no plans to add band powers to the main muselsl library as we assume most users will have their own opinions about how to perform spectral analysis for their particular use case. 

However, we do actually have some code that will compute band powers and provide a "concentration" measure in our [examples folder](https://github.com/alexandrebarachant/muse-lsl/blob/master/examples). Check it out!
