### ISSUE TITLE
Process gyro and acc streaming

### ISSUE THREAD

**Issue by cristinasegalin** [alexandrebarachant/muse-lsl#103]
Hi,
Thanks again for the contribution!
I was trying to get more info from the muse website but there is no longer support or documentation available. So here I am.

How would you process  the streaming of gyro and acc to either visualize them or use them for some computation.. meaning, how to clean (if necessary) the signal and break ot down as done for eeg?

**Comment by jdpigeon** [comment]
Closing because this issue is kind of out of scope with what we can provide with this library. However, convenient viewing of acc and gyro streams is something I plan on adding in the future.
