### ISSUE TITLE
Fails to connect after muselsl list (bluetooth keeps on resetting):

### ISSUE THREAD

**Issue by VictorSaenger** [alexandrebarachant/muse-lsl#105]
Hi MUSE developers/researchers,

I am trying to connect to MUSE 2 using Ubuntu 18.04 but I fail every time and get this error:

`pygatt.exceptions.BLEError: BLE adapter requires reset after a scan as root- call adapter.reset()`
 
I have already tried resetting the bluetooth service but I keep failing to connect. I was able to connect to the device directly through `bluetoothctl`, so pairing works. I guess it has something to do with how Pygatt handles pairing.

Any advice would be greatly appreciated! Another researcher from the place I work has exactly the same problem.

All very best,

**Comment by jdpigeon** [comment]
Sorry that you're running into this.

This is certainly a pygatt issue, so I'm not sure how much help I can give. Have you followed the instructions to give root privileges to `hcitool`? https://github.com/alexandrebarachant/muse-lsl#linux
