### ISSUE TITLE
A problem of Bluetooth compatibility?

### ISSUE THREAD

**Issue by evajosse** [alexandrebarachant/muse-lsl#106]
Hello everyone, 
I spend multiple days trying to stream the data from my Muse 2 headband, either with windows or ubuntu. I followed the steps of the Readme, but also read lots of other issues (for example I tried to do as in issue #1), and the BlueMuse App is still crashing every time, or my computer does not react to the command lines indicated in the forum as it should. So my first question is: Does anyone really manage to stream from Muse 2 using no dongle, nor raspberry... ? If yes, what is the Bluetooth version of your computer? As I saw that my computer has version 4.1 whereas Muse 2 is a 5.0 Bluetooth device. May the application always crash because of this difference? 

Thank to anyone who will take the time to answer.

**Comment by jdpigeon** [comment]
Can you specify what issues you had with Ubuntu? Normally the process of getting setup is pretty painless and just involves giving pygatt root privileges with `sudo setcap 'cap_net_raw,cap_net_admin+eip' `which hcitool``
