### ISSUE TITLE
Where is muse-lsl.py?   

### ISSUE THREAD

**Issue by jscodedeep** [alexandrebarachant/muse-lsl#107]
What's in the muse-lsl.py?

**Comment by jdpigeon** [comment]
`muse-lsl.py` was the filename used in the library before we updated it to be a CLI. If you're seeing that somewhere, please let me know and I'll remove the reference

**Comment by jscodedeep** [comment]
It's from some of the Issues.

Could not install BlueMuse because the certificate has expired, bought BLE112 dongle with Windows 10, tried following commands, all failed or asking BlueMuse, I can see COM4 in the DeviceManager

>muselsl stream -b bgapi
Starting BlueMuse, see BlueMuse window for interactive list of devices.

>muselsl stream -i COM4 -b bgapi
Starting BlueMuse, see BlueMuse window for interactive list of devices.

>muselsl stream -a 00:55:DA:B5:38:CB -b bgapi
Connecting to Muse: 00:55:DA:B5:38:CB...
Connection to 00:55:DA:B5:38:CB failed
