### ISSUE TITLE
PPG ACC GYRO streams not found

### ISSUE THREAD

**Issue by CChilli** [alexandrebarachant/muse-lsl#109]
I tried opening a stream on Windows 10 for all of the Muse 2 sensors using 
`stream( ppg_enabled=True, acc_enabled=True, gyro_enabled=True)`
and received this output 

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-14-90a2bc808ff6> in <module>
> ----> 1 mse.stream(address='00:55:da:b5:3a:cb', ppg_enabled=True, acc_enabled=True, gyro_enabled=True)
> 
> C:\ProgramData\Anaconda3\lib\site-packages\muselsl\stream.py in stream(address, backend, interface, name, ppg_enabled, acc_enabled, gyro_enabled, eeg_disabled)
>     168               (eeg_string, ppg_string, acc_string, gyro_string))
>     169 
> --> 170         while time() - muse.last_timestamp < AUTO_DISCONNECT_DELAY:
>     171             try:
>     172                 sleep(1)
> 
> AttributeError: 'Muse' object has no attribute 'last_timestamp'

Specifying the bluemuse backend avoided the error, but attempting to record anything but EEG states that the stream isn't found. I am not sure if it is a problem in muselsl or BlueMuse.

**Comment by jdpigeon** [comment]
You're running into this issue because BlueMuse unfortunately doesn't support PPG, ACC, or GYRO streams: https://github.com/kowalej/BlueMuse/issues/17
