### ISSUE TITLE
Multiple Muse2 streams simultaneously in windows with pygatt for eeg,acc,gyro,ppg

### ISSUE THREAD

**Issue by benjohn18** [alexandrebarachant/muse-lsl#112]
I have some muse2 and want to use them at the same time to collect eeg,acc,gyro,ppg .
But when I creat a threading for a muse2 ,the secord threading can't stream other muse2.And I run a py file to stream a muse2,the secord time py file I ran can't recognise BLED112.
Can I use a computer to stream multiple muse2? 
Do I need to buy multiple BLED112 to stream multiple muse2 at a computer?

**Comment by jdpigeon** [comment]
Unfortunately people have had a lot of difficulty streaming multiple Muses, both with pygatt and BlueMuse.

Refer to the discussion about multiple device streaming here: https://github.com/alexandrebarachant/muse-lsl/issues/61
