### ISSUE TITLE
Right aux not displayed

### ISSUE THREAD

**Issue by daryllytle** [alexandrebarachant/muse-lsl#113]
The Right Aux channel title and stream is not displayed, only the 4 channels.  Do I need to enable it?

I’m using: Windows 10 Laptop built-in Bluetooth, Bluemuse Streamer, Muse MU-03

Thanks,

Daryl

**Comment by gsajko** [comment]
The Right Aux is more of a placeholder for additional auxiliary electrode. See this:
https://eeg-notebooks.readthedocs.io/en/latest/using_an_extra_electrode_muse.html
