### ISSUE TITLE
Is muse-lsl raw csv recording in mV or V?

### ISSUE THREAD

**Issue by apavlo89** [alexandrebarachant/muse-lsl#132]
Is muse-lsl raw csv recording in mV or V?

**Comment by DerekLomas** [comment]
I'd love to know that!

**Comment by ErikBjare** [comment]
It is microvolts, see:

https://github.com/alexandrebarachant/muse-lsl/blob/3a98035c89132a53eb67d197ccf9f2937977f96f/muselsl/stream.py#L84-L88
