### ISSUE TITLE
Custom neurofeedback protocols  

### ISSUE THREAD

**Issue by apavlo89** [alexandrebarachant/muse-lsl#154]
Are there any plans to add custom neurofeedback protocols? Also is there such an app that can do this already?

**Comment by jdpigeon** [comment]
Neurofeedback is a bit out of scope for what this package tries to accomplish, so no. However, I would be very excited to see neurofeedback protocols using muselsl make their way to the EEG Notebooks project! https://github.com/NeuroTechX/eeg-notebooks
