### ISSUE TITLE
EEG filtering in neurofeedback.py via utils.py

### ISSUE THREAD

**Issue by sunshineinsandiego** [alexandrebarachant/muse-lsl#164]
Hi - Thanks for the helpful neurofeedback code, wondering if you could answer a quick question about the implementation:

In line 22 of `utils.py`:
```
NOTCH_B, NOTCH_A = butter(4, np.array([55, 65]) / (256 / 2), btype='bandstop')
```

- Assuming this filter out all frequencies between 55Hz and 65Hz? I.e. rejects all between 55-65Hz
- Any particular reason these frequencies were chosen?

Thanks!

**Comment by oori** [comment]
AC line frequency in the US (60Hz).

**Comment by sunshineinsandiego** [comment]
Got it thanks!
