### ISSUE TITLE
Muselsl stream disconnects after >5 mins of streaming

### ISSUE THREAD

**Issue by sunshineinsandiego** [alexandrebarachant/muse-lsl#165]
Hi - My muselsl stream disconnects (possibly a time out issue) after about 5 minutes of streaming. Using a Mac OS with a BLED112 dongle. Anyone else have this problem?

**Comment by oori** [comment]
What's your init line?    do you use ACC + PPG ?

**Comment by sunshineinsandiego** [comment]
Just the standard:
```
muselsl stream
```

**Comment by oori** [comment]
Try adding the `-b bgapi` setting, for example:
```
muselsl list -b bgapi
muselsl stream -b bgapi --acc --address <mac:address>
```

**Comment by sunshineinsandiego** [comment]
Thanks, that worked!  Appreciate it.
