### ISSUE TITLE
Breaking change in dependency: Bleak

### ISSUE THREAD

**Issue by ejoebstl** [alexandrebarachant/muse-lsl#186]
Bleak version 0.18 includes a breaking change: 

> (BREAKING) Changed notification callback argument from int to BleakGattCharacteristic. Fixes #759.

I circumvented this by manually installing the previous version (`pip install bleak==0.17.0`), but it would be nice if muse-lsl could be adjusted to accommodate the changes.

**Comment by jdpigeon** [comment]
Thanks for catching this! I think we should be able to merge the update in soon.
https://github.com/alexandrebarachant/muse-lsl/pull/187
