### ISSUE TITLE
Micro "Conflict" between two recent merges? Raising TypeError due to string in logging

### ISSUE THREAD

**Issue by aureateAnatidae** [alexandrebarachant/muse-lsl#213]
It's probably an issue of namespace, but it seems to be conflicting with the % string formatting.

![2024-05-01_08:22:35](https://github.com/alexandrebarachant/muse-lsl/assets/34411014/f285da3c-e810-477f-b497-9004a4714035)

Removing the `int(self.timeout)` from the `logger.info()` line in muse.py seems to fix this. Could someone confirm that this is happening in the git-clone-installed version?

**Comment by jdpigeon** [comment]
I've reverted you PR. If you have some time to clean it up and fix this issue, I'd happily accept another updated version!
