### ISSUE TITLE
Get Data Accelerometer & Gyroscope

### ISSUE THREAD

**Issue by TheChapu** [alexandrebarachant/muse-lsl#23]
Hello,
I'm trying to get the data from the Accelerometer and Gyroscope, to add it to the other data

With an Android app, I inspected the services and found the ones that were used for the EEG Data

#EGG
273e0003-4c4d-454d-96be-f03bac821358
273e0004-4c4d-454d-96be-f03bac821358
273e0005-4c4d-454d-96be-f03bac821358
273e0006-4c4d-454d-96be-f03bac821358
273e0007-4c4d-454d-96be-f03bac821358

and these are "Free"

#Books
273e000A-4c4d-454d-96be-f03bac821358
273e000B-4c4d-454d-96be-f03bac821358
273e0001-4c4d-454d-96be-f03bac821358
273e0002-4c4d-454d-96be-f03bac821358
273e0008-4c4d-454d-96be-f03bac821358
273e0009-4c4d-454d-96be-f03bac821358

Someone here has managed to get the other data

**Comment by alexandrebarachant** [comment]
Hey, 
i think @urish decoded the Accelerometer data for his muse-js repository : https://github.com/urish/muse-js
I will be more than happy if you submit a PR for this :)

**Comment by TheChapu** [comment]
Great,

I'll see how to pass the code to Python.

I'll do tests, if everything goes well, I'll upload it here.

I hope everything goes well

**Comment by TheChapu** [comment]
# I was working a bit and this got,

muse_service = 0xfe8d
 control_characteristic = 273e0001-4c4d-454d-96be-f03bac821358
 telemetry_characteristic = 273e000b-4c4d-454d-96be-f03bac821358
 gyroscope_characteristic = 273e0009-4c4d-454d-96be-f03bac821358
 accelerometer_characteristic = 273e000a-4c4d-454d-96be-f03bac821358

 egg_characteristic = 273e0003-4c4d-454d-96be-f03bac821358,
					   273e0004-4c4d-454d-96be-f03bac821358,
						273e0005-4c4d-454d-96be-f03bac821358,
						273e0006-4c4d-454d-96be-f03bac821358,
						273e0007-4c4d-454d-96be-f03bac821358,
 egg_frequency = 256
 eeg_characteristic = TP9,AF7,AF8,TP10,AUX
 backend = 'gatt'
 pygatt.GATTToolBackend(self.interface)
 interface = 'hci0'

`
import bitstring
import pygatt
import numpy as np
from time import time, sleep
from sys import platform

class Muse():
	
    """Muse 2016 headband"""

    def __init__(self, address=None, callback=None, eeg=True, accelero=True,
                 giro=True,telemetry=True,info=True, backend='auto', interface=None, time_func=time,
                 name=None):
        """Initialize"""
        self.address = address
        self.name = name
        self.callback = callback
        self.eeg = eeg
        self.accelero = accelero
        self.giro = giro
        self.telemetry = telemetry
        self.info = info
        self.interface = interface
        self.time_func = time_func

        if backend in ['auto', 'gatt', 'bgapi']:
            if backend == 'auto':
                if platform == "linux" or platform == "linux2":
                    self.backend = 'gatt'
                else:
                    self.backend = 'bgapi'
            else:
                self.backend = backend
        else:
            raise(ValueError('Backend must be auto, gatt or bgapi'))

    def connect(self, interface=None, backend='auto'):
        """Connect to the device"""

        if self.backend == 'gatt':
            self.interface = self.interface or 'hci0'
            self.adapter = pygatt.GATTToolBackend(self.interface)
        else:
            self.adapter = pygatt.BGAPIBackend(serial_port=self.interface)

        self.adapter.start()

        if self.address is None:
            address = self.find_muse_address(self.name)
            if address is None:
                raise(ValueError("Can't find Muse Device"))
            else:
                self.address = address
        self.device = self.adapter.connect(self.address)
        

        # subscribes to TODO
        if self.eeg:
            self._subscribe_eeg()

    def find_muse_address(self, name=None):
        """look for ble device with a muse in the name"""
        list_devices = self.adapter.scan(timeout=10.5)
        for device in list_devices:
            if name:
                if device['name'] == name:
                    print('Found device %s : %s' % (device['name'],
                                                    device['address']))
                    return device['address']

            elif 'Muse' in device['name']:
                    print('Found device %s : %s' % (device['name'],
                                                    device['address']))
                    return device['address']

        return None

    def start(self):
        """Start streaming."""
        self._init_timestamp_correction()
        self._init_sample()
        self.last_tm = 0
        self.device.char_write_handle(0x000e, [0x02, 0x64, 0x0a], False)

    def stop(self):
        """Stop streaming."""
        self.device.char_write_handle(0x000e, [0x02, 0x68, 0x0a], False)

    def disconnect(self):
        """disconnect."""
        self.device.disconnect()
        self.adapter.stop()

    def _subscribe_eeg(self):
        """subscribe to eeg stream."""
        self.device.subscribe('273e0003-4c4d-454d-96be-f03bac821358',
                              callback=self._handle_eeg)
        self.device.subscribe('273e0004-4c4d-454d-96be-f03bac821358',
                              callback=self._handle_eeg)
        self.device.subscribe('273e0005-4c4d-454d-96be-f03bac821358',
                              callback=self._handle_eeg)
        self.device.subscribe('273e0006-4c4d-454d-96be-f03bac821358',
                              callback=self._handle_eeg)
        self.device.subscribe('273e0007-4c4d-454d-96be-f03bac821358',
                              callback=self._handle_eeg)
        
        """Acc"""                      
        self.device.subscribe('273e000a-4c4d-454d-96be-f03bac821358',
							  callback=self._handle_acc)
		
        """Gyro	Error UUID	"""			   
        #self.device.subscribe('2273e0009-4c4d-454d-96be-f03bac821358',
		#					  callback=self._gyro)
		
        """Telemetry"""					  
        self.device.subscribe('273e000b-4c4d-454d-96be-f03bac821358',
							  callback=self._tele)
        """Control"""					  
        self.device.subscribe('273e0001-4c4d-454d-96be-f03bac821358',
							  callback=self._control)
							  
        """Test 273e0008/9 Data""" 
        #self.device.subscribe('273e0008-4c4d-454d-96be-f03bac821358',
		#					  callback=self._test_0009)
	
	
    def _unpack_acc_channel(self,packet):
		"""Decode data packet of accelerometer"""
		
		a = bitstring.Bits(bytes=packet)
		pattern = "uint:16,uint:16,uint:16,uint:16,uint:16,uint:16,uint:16,uint:16,uint:16,uint:16"
		res = a.unpack(pattern) # Transforma los datos en 16bit y 12 bit
		return res
		
    
    def _unpack_telemetry_channel(self,packet):
		"""Decode Data packet of telemetry channel"""
		a = bitstring.Bits(bytes=packet) #Llega la data y la convierte en bist
		
		pattern = "uint:16,uint:16,uint:16,uint:16,uint:16"
		res = a.unpack(pattern) # Transforma los datos en 16bit y 12 bit

		sequenceID = res[0]
		battery_level=res[1]/512.0
		fuel_gauge_voltaje = res[2]*2.2
		temperature = res[3]
		otro = res[4]
		
		return sequenceID,battery_level,fuel_gauge_voltaje,temperature,otro
        
    def _unpack_eeg_channel(self, packet):
        """Decode data packet of one eeg channel.

        Each packet is encoded with a 16bit timestamp followed by 12 time
        samples with a 12 bit resolution.
        """
        aa = bitstring.Bits(bytes=packet) #Llega la data y la convierte en bist
        #print aa
        pattern = "uint:16,uint:12,uint:12,uint:12,uint:12,uint:12,uint:12, \
                   uint:12,uint:12,uint:12,uint:12,uint:12,uint:12"
        res = aa.unpack(pattern) # Transforma los datos en 16bit y 12 bit
        #print res
        packetIndex = res[0] #Empaqueta el tiempo
        #print packetIndex
        data = res[1:] #Desde el dato 1 hasta el final(12), se aplica formula de conversion
        # 12 bits on a 2 mVpp range
        data = 0.48828125 * (np.array(data) - 2048)
        #print data
        return packetIndex, data #Retorna el dato del tiempo y los 12 datos del Muse, volver a handle_egg

    def _init_sample(self):
        """initialize array to store the samples"""
        self.timestamps = np.zeros(5)
        self.data = np.zeros((5, 12))

    def _init_timestamp_correction(self):
        """Init IRLS params"""
        # initial params for the timestamp correction
        # the time it started + the inverse of sampling rate
        self.sample_index = 0
        self.reg_params = np.array([self.time_func(), 1./256])

    def _update_timestamp_correction(self, x, y):
        """Update regression for dejittering

        use stochastic gradient descent
        """
        pass
    
    
    def _control(self,handle,data):
		""" 14{"rc":0}40022",3238"""
		return handle,data
		
		
    def _handle_acc(self,handle,data):
		"""
		Callback for receiving a sample
		sample are received in this order
		samples: [
                { x: 4579, y: 3485, z: 15475 },
                { x: 4613, y: 3401, z: 15413 },
                { x: 4535, y: 3506, z: 15503 },
            ],
        sequenceId: 21101,
		"""
		#print handle,data
		#handle 23
		d = self._unpack_acc_channel(data)
		#print d
    
    def _gyro(self,handle,data):
		#print handle,data
		pass
    
    
    def _tele(self,handle,data):
		#print handle,data
		"""handle 26
		sequenceId: number
		batteryLevel: number;
		fuelGaugeVoltage: number;
		temperature: number;"""
		d = self._unpack_telemetry_channel(data)
		#print d
		"""Print sequenceID,battery,voltage,temperature, none"""
		    
    
    def _handle_eeg(self, handle, data):
        """Calback for receiving a sample.

        sample are received in this oder : 44, 41, 38, 32, 35
        wait until we get 35 and call the data callback
        """
        timestamp = self.time_func()
        #print handle,data
        index = int((handle - 32) / 3) #Para ordenar los datos 4,3,2,0,1
        #print handle,index
        tm, d = self._unpack_eeg_channel(data) #Se llama a la funcion y se envia la data, esta retorna tm,d
        #tm es tiempo
        #d es data

        if self.last_tm == 0:
            self.last_tm = tm - 1

        self.data[index] = d #Toda la data se va a data[index]
        self.timestamps[index] = timestamp #Toda la data se va a timestamps[index]
        # last data received
        #Si el ultimo dato es = 35
        if handle == 35:
			#Si el tiempo es distinto
            if tm != self.last_tm + 1:
                print("missing sample %d : %d" % (tm, self.last_tm))
            self.last_tm = tm

            # calcultate index of time samples
            # Calcula el indice de muestras en el tiempo
            idxs = np.arange(0, 12) + self.sample_index
            self.sample_index += 12

            # affect as timestamps
            # Afeecta a timestamp
            timestamps = self.reg_params[1] * idxs + self.reg_params[0]

            # push data
            # Se envia la data a la funcion #callback
            self.callback(self.data, timestamps)
            self._init_sample()
`

Build 2 new functions to obtain Acc data, Telemetry data
I'm still not sure if the data I get is correct

**Comment by luzpaz** [comment]
Is this ready to be submit as a PR ?

**Comment by alexandrebarachant** [comment]
hey, @urish made some progress on decoding gyroscope and accelero data : https://github.com/urish/muse-js/commit/66a8eba78570300e580c9ae47d379e7f9d6ddc8b

@TheChapu can you please make a [pull request](https://github.com/PointCloudLibrary/pcl/wiki/A-step-by-step-guide-on-preparing-and-submitting-a-pull-request) with your changes so i can try and review your code.

**Comment by TheChapu** [comment]
hey @alexandrebarachant 
I have created a repository so as not to spoil yours :F

Please review. https://github.com/TheChapu/Muse-Python

I have obtained the data of the Accelerometer and Gyroscope, taking as an example the code of @urish 

Please check it and tell me to update

**Comment by alexandrebarachant** [comment]
great, the intent is good, but this way I can not check changes and merge your modifications easily (it will require a lot of extra manual work).

The usual way to do this on github is to : 
1. fork the repository (i.e. create a copy in your own account) by using the fork button
2. create a new branch with your modifications
3. submit a pull request.

**Comment by TheChapu** [comment]
![screenshot at 2017-12-26 13-39-32](https://user-images.githubusercontent.com/13274956/34360733-3f59e16a-ea42-11e7-8a06-2d9016b806e6.png)

**Comment by alexandrebarachant** [comment]
almost there. you have to submit the pull request to my repository (not yours)

**Comment by TheChapu** [comment]
Sorry.

Can you look again?

Thank you

**Comment by alexandrebarachant** [comment]
hey, 

go to this page : https://github.com/alexandrebarachant/muse-lsl/pulls

click on 'new pull request', then select your brqnch qnd submit it.

**Comment by TheChapu** [comment]
![screenshot at 2017-12-28 11-27-15](https://user-images.githubusercontent.com/13274956/34413419-35ad64a8-ebc2-11e7-9d97-dd9f2dffff93.png)

**Comment by TheChapu** [comment]
I see the image.

I'm sorry, but it's the first time I use Github to help

**Comment by alexandrebarachant** [comment]
you probably have to click on "compare across forks" then select your branch containing your modification and my master branch.

don't worry, we all had to make our first PR someday :)

**Comment by TheChapu** [comment]
At last :+1: 
I won a coffee  


![screenshot at 2017-12-28 12-01-48](https://user-images.githubusercontent.com/13274956/34414243-eafd2074-ebc6-11e7-8d87-34107e32f851.png)
![screenshot at 2017-12-28 12-01-21](https://user-images.githubusercontent.com/13274956/34414244-eb1c1c9a-ebc6-11e7-827c-90419b9185ae.png)

**Comment by jdpigeon** [comment]
Address by https://github.com/alexandrebarachant/muse-lsl/pull/93
