### ISSUE TITLE
Error when running lsl-record.py

### ISSUE THREAD

**Issue by ranibourbara** [alexandrebarachant/muse-lsl#24]
Hi,

Although it worked before, somehow lsl-record.py throws an error:
looking for an EEG stream...
Start aquiring data
looking for a Markers stream...
-3.19054997817e-05
Start recording at time t=1513856020.623
Traceback (most recent call last):
  File "lsl-record.py", line 66, in <module>
    max_samples=12)
  File "C:\Users\R\Anaconda2\lib\site-packages\pylsl\pylsl.py", line 799, in pull_chunk
    byref(errcode))
WindowsError: exception: access violation reading 0x00007A5611F54038

while lsl-viewer.py works just fine.

Any suggestions would be appreciated

Thank you

**Comment by alexandrebarachant** [comment]
is this error occurring every time you run lsl-record ?
it looks like a low level lsl error to me. can you try updating pylsl ?
