### ISSUE TITLE
BLED112 dongle?

### ISSUE THREAD

**Issue by fromnear** [alexandrebarachant/muse-lsl#3]
![20170420_152114](https://cloud.githubusercontent.com/assets/22868225/25216340/159fa26c-25dd-11e7-94cc-f39773f23ae1.png)

1. At the first I got "pygatt.exceptions.NotConnectedError: No BGAPI compatible device detected" message.
After search, I changed the code row 14, None to "COM1"

2. then I could get different message, "pygatt.backends.bgapi.exceptions.ExpectedResponseTimeout: Timed out after 1.000000s waiting for [<ResponsePacketType.gap_set_mode: 58>"

I am using Next v10.10 Bluetooth 4.0 usb dongle(Korean company), Python 3.5.2, Windows 10 Pro, Muse 2016. What would be problem?

Q1. Is a bluetooth dongle must be USB dongles made by Bluegiga, BLED112 only?
Does the codes works on other bluetooth low energy 4.0 dongles?

Q2. Do I have to use Bluesoleil things for pairing? or just OK with basic windown bluetooth tool?

It will be very nice if I could run your code. :)

**Comment by alexandrebarachant** [comment]
Hi,

1. The first error is because pygatt is looking for a BLED112 dongle, so auto-detection does not work with other dongle. you have to specify the COM port manually.
2. The second error appears during initialization of the dongle. The protocol is probably different / incompatible so the code raise an error when the dongle does not respond.

Q1. I think that's a question to ask to the pygatt authors https://github.com/peplin/pygatt

Q2. You don't need to pair the device at all.

**Comment by fromnear** [comment]
Ok, I'll try to ask to pygatt authors. Please check the followings before I close this.

1. Have you tried your code on windows? Because pygatt authors said "GATTToolBackend requires Linux (i.e. not Windows compatible)". And you said "pygatt works on linux and should work on window and OSX provided that you have a BLED112 dongle". I wonder what "should work on windows" supposed to mean.

2. Do you use Blugiga BLED112 dongle? Does it look like this? I want to confirm it before I order one.
![untitled](https://cloud.githubusercontent.com/assets/22868225/25225526/a3093b44-25fc-11e7-945e-84e39c5688a4.png)

**Comment by alexandrebarachant** [comment]
1. Yes, i tried on windows with a BLED112 dongle. The code works (you have to install pygatt from the sources). I will update the README.

2. Yes, this is the dongle.

**Comment by fromnear** [comment]
Very kind of you. Thank you for quick answer.
I appreciate that.

I'll try your code with that dongle. Order one over the pacific ocean. Hope it will work.

**Comment by alexandrebarachant** [comment]
The other solution is to boot with ubuntu on a liveUSB :) should works out of the box (once you installed python)
