### ISSUE TITLE
I get an error when trying to find my muse MAC with scan_devices.py

### ISSUE THREAD

**Issue by deviousname** [alexandrebarachant/muse-lsl#31]
Also when I try to run muse-lsl.py, I get the same error:
(Ubuntu 16.04)
"pygatt.eceptions.BLEError: Unexpected error when scanning: Set scan parameters failed: Operation not permitted"

**Comment by alexandrebarachant** [comment]
this is a permission error when trying to scan. 
This can be fixed with : 

```
sudo setcap 'cap_net_raw,cap_net_admin+eip' `which hcitool` 
```
