### ISSUE TITLE
BLEError, no characteristic found matching UUID

### ISSUE THREAD

**Issue by pdpino** [alexandrebarachant/muse-lsl#4]
Hi,
I get the following error when trying to connect to the headband:
`pygatt.exceptions.BLEError: No characteristic found matching 273e0003-4c4d-454d-96be-f03bac821358`
which is raised when trying to subscribe the first eeg channel in the `_subscribe_eeg()` method. The weird part is that until a week ago I used the same code and it worked fine, I was able to connect and receive data from the heaband.

I tried connecting with the headband via `gatttool`, and I saw that there is no uuid matching the one from the error on the list (only one that is almost the same):
![char-desc](https://cloud.githubusercontent.com/assets/20805451/25552628/71dd5292-2c75-11e7-9ad2-9698de9a10f8.png)
![uuids](https://cloud.githubusercontent.com/assets/20805451/25552658/f7b7cd70-2c75-11e7-82e1-07f1162fe870.png)

Although I am new with bluetooth connections, so I'm not sure if this is relevant at all. Any ideas?
Thanks!

**Comment by alexandrebarachant** [comment]
Interesting.
Is this error recurrent i.e happens every times ?

i really have no idea where it came from.

**Comment by pdpino** [comment]
It happened just the one time.
After about a day of trying everything (power off and on, disconnect bluetooth adapter, pair unpair, block unblock, trust untrust, charging battery, etc) using `hcitool`, `gatttool` and `bluetoothctl`, I don't know how but it got fixed (I don't even know if it was something that I did or not). 
Anyway, thanks again.

**Comment by alexandrebarachant** [comment]
Ok thanks for the update.

pygatt scans the uuid before it can subscribes to it. It might have happened that the muse timed out before sending the complete list. 

I'm closing the issue, but this remains a mystery.

**Comment by jdpigeon** [comment]
Getting this error with one of my headbands. Very mysterious. 

My other headband works, though.

**Comment by pdpino** [comment]
Check the pygatt version (see README, common issues: [link](https://github.com/alexandrebarachant/muse-lsl/blob/master/README.md#common-issues)).
Another option is charging the battery.
If neither works I have no clue.

**Comment by jdpigeon** [comment]
After turning headband on and off and connecting to it through EEG 101 (unusually long connection time) it's working. Definitely a hardware issue.
