### ISSUE TITLE
lsl-record.py on mac

### ISSUE THREAD

**Issue by amandakeasson** [alexandrebarachant/muse-lsl#45]
lsl-record.py, line 35:
marker_streams = resolve_byprop('name', 'Markers', timeout=2)

The timeout period was not long enough when I ran this on my Macbook, so the marker stream was not found.

Increasing the timeout period to 10s fixed the problem.

**Comment by jdpigeon** [comment]
Increased the timeout here: https://github.com/alexandrebarachant/muse-lsl/commit/ef7903bd79d7fa950e6e15e7f48307704dc48560

Hopefully that helps!
