### ISSUE TITLE
lsl-viewer doesn't work over ssh/X forwarding

### ISSUE THREAD

**Issue by jona-sassenhagen** [alexandrebarachant/muse-lsl#5]
My ideal setup would be to ssh over wifi into my raspberry pi. However, `lsl-viewer.py` doesn't work that way - it only shows one frame and then halts. This means I can't check if my channels are connected without buying a monitor for my Pi. Is this something that could in principle be solved, or is updated MPL over ssh/X forwarding not possible?

**Comment by alexandrebarachant** [comment]
LSL is accessible through local network.
you can run muse-lsl.py on the raspberry, and run the lsl-viewer on any computer on your local network.

**Comment by jona-sassenhagen** [comment]
Ah! That's interesting. I'll see if I can get that set up.

**Comment by aj-ptw** [comment]
I've been trying to get this working too. I get error 
```
OSError: /usr/local/lib/python2.7/dist-packages/pylsl/liblsl32.so: cannot open shared object file: No such file or directory
```

I think the program ran properly the first time. But even when the script ran the first time on the PI i could not see a stream with `lsl-viewer.py` and `lsl-viewer-V2.py` failed with a different error.
