### ISSUE TITLE
Unfindable packages on Mac

### ISSUE THREAD

**Issue by jdpigeon** [alexandrebarachant/muse-lsl#54]
Installing through pip3 on a Mac computer, we ran into issues related to `nose` and `coverage`. We were able to get around this by installing those libraries directly

**Comment by dxjones** [comment]
for novice python/pip folks, struggling to get this working, ... what are the workaround steps for installing "nose" and "coverage" ??

**Comment by jdpigeon** [comment]
`pip install nose coverage'
