### ISSUE TITLE
Getting "missing sample" ?

### ISSUE THREAD

**Issue by maxihidara** [alexandrebarachant/muse-lsl#67]
Hi, i am usually getting "missing sample" when stream and run exercise 2 from bci workshop python file. I have tried the solution from previous issue but get error when i run given script, and i don't really understand about it. I am using raspberry pi 3 and muse 2016. Can anyone help ? Thank  you

**Comment by maxihidara** [comment]
Is using another bluetooth adapter (not raspi built in bluetooth adapter) fix the problem ?

Nope, never happens to me that issue

**Comment by jdpigeon** [comment]
Yea, if you can get a BlueGiga BLED112 dongle, that might be able to solve your issues

**Comment by maxihidara** [comment]
Is there another bluetooth dongle that compatible with muse eeg ? Because i can find online seller who sell it in my country.

**Comment by maxihidara** [comment]
I mean other than bluegiga bled112

**Comment by jdpigeon** [comment]
There may be, but we've encountered lots of dongles that don't work. Our strategy is just to recommend BlueGiga BLED112. If you talk to a hardware specialist, they could hopefully point you to one that may be compatible

**Comment by maxihidara** [comment]
I just check my raspberry's bluetooth specification, it says that my raspberry pi 3 model b, using 4.1 bluetooth version, and if i am not wrong, muse eeg 2016 using 4.0 bluetooth.

**Comment by maxihidara** [comment]
I have solved it. I use eksternal bluetooth dongle (not bluegiga). It's right what jdpigeon said that raspberry pi bluetooth have bad performance
