### ISSUE TITLE
Resource Busy Error during connection attempt with BLED112

### ISSUE THREAD

**Issue by eteters** [alexandrebarachant/muse-lsl#75]
On Mac, in terminal  - 

I am seeing an error when trying to establish a connection with a Muse 2016.

`muselsl list`  results in 

`Traceback (most recent call last):
  File "/Users/evanteters/anaconda3/lib/python3.6/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
OSError: [Errno 16] Resource busy: '/dev/cu.usbmodem1'`

I tried addressing the issue through using `muselsl list --interface /dev/cu.usbmodem1`
but this still gave an error. This time: 

`File "/Users/evanteters/anaconda3/lib/python3.6/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
OSError: [Errno 6] Device not configured: '/dev/cu.usbmodem1'`

I'm running High Sierra 10.13.6, and using  [BLED112-V1](https://www.silabs.com/products/wireless/bluetooth/bluetooth-low-energy-modules/bled112-bluetooth-smart-dongle) manufactured by Silicon Labs

I tried to find other processes accessing the same port but it seemed nothing was using it. 

Thanks for the help!

**Comment by oori** [comment]
This is an old issue with `pygatt` version 3, see: https://github.com/peplin/pygatt/issues/159
There are two solution, either:
a. Upgrade pygatt > 4  ```pip install -U pygatt```
b. Use the `time.sleep(2)` hack, as explain here: https://github.com/peplin/pygatt/issues/159#issuecomment-398660108
