### ISSUE TITLE
muse-lsl.py : stream outlet error

### ISSUE THREAD

**Issue by shivam2298** [alexandrebarachant/muse-lsl#76]
python version - Python 3.6.7
ubuntu 18.04 

I have all the packages installed as mentioned in the bci-workshop repo. When I run the muse-lsl.py, 
I get the following error :

> Unexpected error during construction of stream outlet: lslboost::condition_variable::condition_variable() constructor failed in pthread::cond_init: Invalid argument
> Traceback (most recent call last):
>   File "muse-lsl.py", line 35, in <module>
>     outlet = StreamOutlet(info, 12, 360)
>   File "/home/shivam/.local/lib/python3.6/site-packages/pylsl/pylsl.py", line 409, in __init__
>     raise RuntimeError("could not create stream outlet.")
> RuntimeError: could not create stream outlet.
> 
Please can somebody help me out in this.

**Comment by jdpigeon** [comment]
You're having the same issue identified in https://github.com/alexandrebarachant/muse-lsl/issues/72

I believe the solution may be just ensuring you have the right version of the pylsl dependency. Check that issue for discussion
