### ISSUE TITLE
Starting python code after a stream has started

### ISSUE THREAD

**Issue by edmogeor** [alexandrebarachant/muse-lsl#86]
Anyone have any ideas on how I would connect & start a stream then run a custom python function automatically once the stream had started?

Trying to implement this as part of a raspberry pi project, the code would have to start on boot of the pi.

any help would be appreciated!

Thanks

**Comment by jdpigeon** [comment]
Hey @edmogeor.

Sounds like a cool project! I've done something similar with a pi before and would recommend looking into using cron to start a python script on boot. This tutorial might be helpful: https://learn.pimoroni.com/tutorial/sandyj/running-scripts-at-boot

In that python script you could import and muse-lsl's stream function, although you may need to use multithreading to get what you want (there's an example in [eeg notebooks](https://github.com/NeuroTechX/eeg-notebooks)).

A more hacky but potentially simpler solution would be to start two different python scripts on boot with cron and have the second custom python script use an interval function to wait for a successful muse lsl stream to start.
