### ISSUE TITLE
Reference Electrode

### ISSUE THREAD

**Issue by X3N1A** [alexandrebarachant/muse-lsl#91]
Hello, is there any way to get the reference electrode data from the muse?
I am new to python, is this the variable I need to add to stream.py? 
MUSE_GATT_ATTR_STREAM_TOGGLE = '273e0001-4c4d-454d-96be-f03bac821358'
Thanks

**Comment by jdpigeon** [comment]
I don't think the reference electrode is accessible. @stepheninx?

**Comment by alexandrebarachant** [comment]
reference electrode are usually not accessible since the referencing is done on hardware. I dont think the muse device allow to access it.
